package email

import (
	"bytes"
	"fmt"
	"html/template"
	"net/smtp"
	"strings"

	"github.com/jiin/stale/internal/domain"
	"github.com/rs/zerolog/log"
)

type Service struct{}

func New() *Service {
	return &Service{}
}

func (s *Service) SendNewOutdatedReport(settings *domain.Settings, report *domain.NewOutdatedReport) error {
	if !settings.EmailEnabled {
		return nil
	}

	if len(report.NewOutdated) == 0 {
		log.Debug().Msg("no new outdated dependencies to report")
		return nil
	}

	subject := fmt.Sprintf("[Stale] %d new outdated dependencies found", len(report.NewOutdated))
	body, err := s.buildEmailBody(report)
	if err != nil {
		return fmt.Errorf("failed to build email body: %w", err)
	}

	return s.sendMail(settings, subject, body)
}

func (s *Service) buildEmailBody(report *domain.NewOutdatedReport) (string, error) {
	tmpl := `<!DOCTYPE html>
<html>
<head>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
.container { max-width: 800px; margin: 0 auto; background: white; border-radius: 8px; padding: 24px; }
h1 { color: #1a1a1a; font-size: 24px; margin: 0 0 16px 0; }
.summary { color: #666; margin-bottom: 24px; }
table { width: 100%; border-collapse: collapse; }
th { text-align: left; padding: 12px; background: #f8f9fa; border-bottom: 2px solid #dee2e6; color: #495057; font-weight: 600; }
td { padding: 12px; border-bottom: 1px solid #dee2e6; }
.repo { color: #0066cc; }
.dep { font-weight: 500; }
.version { font-family: monospace; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
.current { background: #fff3cd; color: #856404; }
.latest { background: #d4edda; color: #155724; }
.ecosystem { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
.npm { background: #cb3837; color: white; }
.maven { background: #c71a36; color: white; }
.gradle { background: #02303a; color: white; }
.go { background: #00add8; color: white; }
.footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #dee2e6; color: #6c757d; font-size: 14px; }
</style>
</head>
<body>
<div class="container">
<h1>New Outdated Dependencies Found</h1>
<p class="summary">{{len .NewOutdated}} new outdated dependencies were detected during scan #{{.ScanID}}.</p>
<table>
<tr>
<th>Repository</th>
<th>Dependency</th>
<th>Current</th>
<th>Latest</th>
<th>Ecosystem</th>
</tr>
{{range .NewOutdated}}
<tr>
<td class="repo">{{.RepoFullName}}</td>
<td class="dep">{{.Name}}</td>
<td><span class="version current">{{.CurrentVersion}}</span></td>
<td><span class="version latest">{{.LatestVersion}}</span></td>
<td><span class="ecosystem {{.Ecosystem}}">{{.Ecosystem}}</span></td>
</tr>
{{end}}
</table>
<div class="footer">
This report was generated by Stale - Dependency Version Dashboard
</div>
</div>
</body>
</html>`

	t, err := template.New("email").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, report); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (s *Service) sendMail(settings *domain.Settings, subject, body string) error {
	addr := fmt.Sprintf("%s:%d", settings.EmailSMTPHost, settings.EmailSMTPPort)

	recipients := strings.Split(settings.EmailTo, ",")
	for i, r := range recipients {
		recipients[i] = strings.TrimSpace(r)
	}

	msg := fmt.Sprintf("From: %s\r\n"+
		"To: %s\r\n"+
		"Subject: %s\r\n"+
		"MIME-Version: 1.0\r\n"+
		"Content-Type: text/html; charset=UTF-8\r\n"+
		"\r\n"+
		"%s",
		settings.EmailFrom,
		settings.EmailTo,
		subject,
		body,
	)

	var auth smtp.Auth
	if settings.EmailSMTPUser != "" && settings.EmailSMTPPass != "" {
		auth = smtp.PlainAuth("", settings.EmailSMTPUser, settings.EmailSMTPPass, settings.EmailSMTPHost)
	}

	err := smtp.SendMail(addr, auth, settings.EmailFrom, recipients, []byte(msg))
	if err != nil {
		log.Error().Err(err).Str("to", settings.EmailTo).Msg("failed to send email")
		return fmt.Errorf("failed to send email: %w", err)
	}

	log.Info().
		Str("to", settings.EmailTo).
		Int("new_outdated", len(recipients)).
		Msg("email notification sent")

	return nil
}

func (s *Service) TestConnection(settings *domain.Settings) error {
	addr := fmt.Sprintf("%s:%d", settings.EmailSMTPHost, settings.EmailSMTPPort)

	var auth smtp.Auth
	if settings.EmailSMTPUser != "" && settings.EmailSMTPPass != "" {
		auth = smtp.PlainAuth("", settings.EmailSMTPUser, settings.EmailSMTPPass, settings.EmailSMTPHost)
	}

	// Send a test email
	subject := "[Stale] Test Email"
	body := `<!DOCTYPE html>
<html>
<body style="font-family: sans-serif; padding: 20px;">
<h2>Test Email from Stale</h2>
<p>If you received this email, your SMTP settings are configured correctly.</p>
</body>
</html>`

	recipients := strings.Split(settings.EmailTo, ",")
	for i, r := range recipients {
		recipients[i] = strings.TrimSpace(r)
	}

	msg := fmt.Sprintf("From: %s\r\n"+
		"To: %s\r\n"+
		"Subject: %s\r\n"+
		"MIME-Version: 1.0\r\n"+
		"Content-Type: text/html; charset=UTF-8\r\n"+
		"\r\n"+
		"%s",
		settings.EmailFrom,
		settings.EmailTo,
		subject,
		body,
	)

	return smtp.SendMail(addr, auth, settings.EmailFrom, recipients, []byte(msg))
}
