package email

import (
	"bytes"
	"crypto/tls"
	"fmt"
	"html/template"
	"net"
	"net/smtp"
	"strings"
	"time"

	"github.com/jiin/stale/internal/domain"
	"github.com/rs/zerolog/log"
)

type Service struct{}

func New() *Service {
	return &Service{}
}

func (s *Service) SendNewOutdatedReport(settings *domain.Settings, report *domain.NewOutdatedReport) error {
	if !settings.EmailEnabled {
		return nil
	}

	if len(report.NewOutdated) == 0 {
		log.Debug().Msg("no new outdated dependencies to report")
		return nil
	}

	subject := fmt.Sprintf("[Stale] %d new outdated dependencies found", len(report.NewOutdated))
	body, err := s.buildEmailBody(report)
	if err != nil {
		return fmt.Errorf("failed to build email body: %w", err)
	}

	return s.sendMail(settings, subject, body)
}

func (s *Service) buildEmailBody(report *domain.NewOutdatedReport) (string, error) {
	tmpl := `<!DOCTYPE html>
<html>
<head>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
.container { max-width: 800px; margin: 0 auto; background: white; border-radius: 8px; padding: 24px; }
h1 { color: #1a1a1a; font-size: 24px; margin: 0 0 16px 0; }
.summary { color: #666; margin-bottom: 24px; }
table { width: 100%; border-collapse: collapse; }
th { text-align: left; padding: 12px; background: #f8f9fa; border-bottom: 2px solid #dee2e6; color: #495057; font-weight: 600; }
td { padding: 12px; border-bottom: 1px solid #dee2e6; }
.repo { color: #0066cc; }
.dep { font-weight: 500; }
.version { font-family: monospace; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
.current { background: #fff3cd; color: #856404; }
.latest { background: #d4edda; color: #155724; }
.ecosystem { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
.npm { background: #cb3837; color: white; }
.maven { background: #c71a36; color: white; }
.gradle { background: #02303a; color: white; }
.go { background: #00add8; color: white; }
.footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #dee2e6; color: #6c757d; font-size: 14px; }
</style>
</head>
<body>
<div class="container">
<h1>New Outdated Dependencies Found</h1>
<p class="summary">{{len .NewOutdated}} new outdated dependencies were detected during scan #{{.ScanID}}.</p>
<table>
<tr>
<th>Repository</th>
<th>Dependency</th>
<th>Current</th>
<th>Latest</th>
<th>Ecosystem</th>
</tr>
{{range .NewOutdated}}
<tr>
<td class="repo">{{.RepoFullName}}</td>
<td class="dep">{{.Name}}</td>
<td><span class="version current">{{.CurrentVersion}}</span></td>
<td><span class="version latest">{{.LatestVersion}}</span></td>
<td><span class="ecosystem {{.Ecosystem}}">{{.Ecosystem}}</span></td>
</tr>
{{end}}
</table>
<div class="footer">
This report was generated by Stale - Dependency Version Dashboard
</div>
</div>
</body>
</html>`

	t, err := template.New("email").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, report); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (s *Service) sendMail(settings *domain.Settings, subject, body string) error {
	recipients := strings.Split(settings.EmailTo, ",")
	for i, r := range recipients {
		recipients[i] = strings.TrimSpace(r)
	}

	msg := fmt.Sprintf("From: %s\r\n"+
		"To: %s\r\n"+
		"Subject: %s\r\n"+
		"MIME-Version: 1.0\r\n"+
		"Content-Type: text/html; charset=UTF-8\r\n"+
		"\r\n"+
		"%s",
		settings.EmailFrom,
		settings.EmailTo,
		subject,
		body,
	)

	log.Info().
		Int("port", settings.EmailSMTPPort).
		Str("host", settings.EmailSMTPHost).
		Msg("sending email")

	var err error
	if settings.EmailSMTPPort == 465 {
		log.Info().Msg("using SSL mode (port 465)")
		err = s.sendMailSSL(settings, recipients, []byte(msg))
	} else {
		log.Info().Msg("using STARTTLS mode")
		err = s.sendMailSTARTTLS(settings, recipients, []byte(msg))
	}

	if err != nil {
		log.Error().Err(err).Str("to", settings.EmailTo).Msg("failed to send email")
		return fmt.Errorf("failed to send email: %w", err)
	}

	log.Info().
		Str("to", settings.EmailTo).
		Int("recipients", len(recipients)).
		Msg("email notification sent")

	return nil
}

// sendMailSTARTTLS sends email using STARTTLS (port 587)
func (s *Service) sendMailSTARTTLS(settings *domain.Settings, recipients []string, msg []byte) error {
	// Use net.JoinHostPort for proper IPv6 support (e.g., [::1]:587)
	addr := net.JoinHostPort(settings.EmailSMTPHost, fmt.Sprintf("%d", settings.EmailSMTPPort))

	// Connect to the SMTP server
	conn, err := net.DialTimeout("tcp", addr, 30*time.Second)
	if err != nil {
		return fmt.Errorf("connection failed: %w", err)
	}
	defer conn.Close()

	// Create SMTP client
	client, err := smtp.NewClient(conn, settings.EmailSMTPHost)
	if err != nil {
		return fmt.Errorf("SMTP client creation failed: %w", err)
	}
	defer client.Close()

	// Send EHLO
	if err := client.Hello("localhost"); err != nil {
		return fmt.Errorf("EHLO failed: %w", err)
	}

	// Start TLS with correct hostname
	tlsConfig := &tls.Config{
		ServerName: settings.EmailSMTPHost,
	}
	if err := client.StartTLS(tlsConfig); err != nil {
		return fmt.Errorf("STARTTLS failed: %w", err)
	}

	// Authenticate
	if settings.EmailSMTPUser != "" && settings.EmailSMTPPass != "" {
		auth := smtp.PlainAuth("", settings.EmailSMTPUser, settings.EmailSMTPPass, settings.EmailSMTPHost)
		if err := client.Auth(auth); err != nil {
			return fmt.Errorf("authentication failed: %w", err)
		}
	}

	// Set sender
	if err := client.Mail(settings.EmailFrom); err != nil {
		return fmt.Errorf("MAIL FROM failed: %w", err)
	}

	// Set recipients
	for _, rcpt := range recipients {
		if err := client.Rcpt(rcpt); err != nil {
			return fmt.Errorf("RCPT TO failed: %w", err)
		}
	}

	// Send message body
	w, err := client.Data()
	if err != nil {
		return fmt.Errorf("DATA failed: %w", err)
	}

	_, err = w.Write(msg)
	if err != nil {
		return fmt.Errorf("write message failed: %w", err)
	}

	err = w.Close()
	if err != nil {
		return fmt.Errorf("close writer failed: %w", err)
	}

	return client.Quit()
}

// sendMailSSL sends email using implicit TLS/SSL (port 465)
func (s *Service) sendMailSSL(settings *domain.Settings, recipients []string, msg []byte) error {
	addr := fmt.Sprintf("%s:%d", settings.EmailSMTPHost, settings.EmailSMTPPort)

	log.Info().Str("addr", addr).Msg("attempting SSL connection to SMTP server")

	// Try to resolve hostname first for debugging
	ips, err := net.LookupIP(settings.EmailSMTPHost)
	if err != nil {
		log.Error().Err(err).Str("host", settings.EmailSMTPHost).Msg("DNS lookup failed")
		return fmt.Errorf("DNS lookup failed for %s: %w", settings.EmailSMTPHost, err)
	}
	log.Info().Strs("ips", func() []string {
		var s []string
		for _, ip := range ips {
			s = append(s, ip.String())
		}
		return s
	}()).Msg("DNS resolved")

	tlsConfig := &tls.Config{
		ServerName: settings.EmailSMTPHost,
	}

	conn, err := tls.DialWithDialer(
		&net.Dialer{Timeout: 30 * time.Second},
		"tcp",
		addr,
		tlsConfig,
	)
	if err != nil {
		log.Error().Err(err).Str("addr", addr).Msg("TLS dial failed")
		return fmt.Errorf("TLS dial failed to %s: %w", addr, err)
	}
	defer conn.Close()

	log.Info().Msg("TLS connection established")

	client, err := smtp.NewClient(conn, settings.EmailSMTPHost)
	if err != nil {
		return fmt.Errorf("SMTP client creation failed: %w", err)
	}
	defer client.Close()

	// Authenticate
	if settings.EmailSMTPUser != "" && settings.EmailSMTPPass != "" {
		auth := smtp.PlainAuth("", settings.EmailSMTPUser, settings.EmailSMTPPass, settings.EmailSMTPHost)
		if err := client.Auth(auth); err != nil {
			return fmt.Errorf("authentication failed: %w", err)
		}
	}

	// Set sender
	if err := client.Mail(settings.EmailFrom); err != nil {
		return fmt.Errorf("MAIL FROM failed: %w", err)
	}

	// Set recipients
	for _, rcpt := range recipients {
		if err := client.Rcpt(rcpt); err != nil {
			return fmt.Errorf("RCPT TO failed: %w", err)
		}
	}

	// Send message body
	w, err := client.Data()
	if err != nil {
		return fmt.Errorf("DATA failed: %w", err)
	}

	_, err = w.Write(msg)
	if err != nil {
		return fmt.Errorf("write message failed: %w", err)
	}

	err = w.Close()
	if err != nil {
		return fmt.Errorf("close writer failed: %w", err)
	}

	return client.Quit()
}

func (s *Service) TestConnection(settings *domain.Settings) error {
	// Send a test email
	subject := "[Stale] Test Email"
	body := `<!DOCTYPE html>
<html>
<body style="font-family: sans-serif; padding: 20px;">
<h2>Test Email from Stale</h2>
<p>If you received this email, your SMTP settings are configured correctly.</p>
</body>
</html>`

	recipients := strings.Split(settings.EmailTo, ",")
	for i, r := range recipients {
		recipients[i] = strings.TrimSpace(r)
	}

	msg := fmt.Sprintf("From: %s\r\n"+
		"To: %s\r\n"+
		"Subject: %s\r\n"+
		"MIME-Version: 1.0\r\n"+
		"Content-Type: text/html; charset=UTF-8\r\n"+
		"\r\n"+
		"%s",
		settings.EmailFrom,
		settings.EmailTo,
		subject,
		body,
	)

	if settings.EmailSMTPPort == 465 {
		return s.sendMailSSL(settings, recipients, []byte(msg))
	}
	return s.sendMailSTARTTLS(settings, recipients, []byte(msg))
}
